version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: cafe-test
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - /home/app/cafeappbackend/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=62597

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email s201729@student.dtu.dk --agree-tos --no-eff-email --force-renewal -d group13.bhsi.xyz.com -d group13.bhsi.xyz

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/app/cafeappbackend/views/
      o: bind

  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/app/cafeappbackend/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge